### ISSUE TITLE
Не работает!

### ISSUE THREAD

**Issue by maksimf** [bodrovis/Sitepoint-source#1]

**Comment by bodrovis** [comment]
Странно писать это участнику GitHub с 2011 года, но всё же.
- Желательно писать по-английски, так как ровно такая же ошибка может быть у других людей, по-русски не понимающих.
- Что не работает?
- В каком проекте?
- Какая ошибка?
- Желательно указать релевантный код, если он был как-то изменён после прочтения статьи.

Поймите меня правильно, мне регулярно присылают не один и не два вопроса, в том числе с просьбами помочь починить что-то неработающее, так что чем больше исходной информации я буду иметь, тем быстрее сумеем разобраться.

**Comment by maksimf** [comment]
Виноват, создал человеческий issue

**Comment by bodrovis** [comment]
Спасибо!
