### ISSUE TITLE
How can i do if i have 2 devise users models ?

### ISSUE THREAD

**Issue by ghost** [bodrovis/Sitepoint-source#10]
Hey

At the first time, thank you so much for this code :+1: 
I need something similar on my app but I have 2 devise models users : Campeur and Proprietaire.

How can I do to implement this code on my app with my 2 users models ?

Some precisions :
In my app, Campeur can engage the conversation to Proprietaire. Campeur can't engage the conversation to another Campeur. Proprietaire can respond only if one Campeur engage the conversation. Proprietaire cant engage the conversation with another Proprietaire.

**Comment by bodrovis** [comment]
@nicolaswecandoit Good day! Please refer to https://github.com/bodrovis/Sitepoint-source/blob/master/CONTRIBUTING.md Which article are we talking about?

**Comment by ghost** [comment]
I m sorry I m talking about the last one https://www.sitepoint.com/build-a-messaging-system-with-rails-and-actioncable/

**Comment by bodrovis** [comment]
I believe you'll need some authorization system. So when someone creates a new conversation you basically check whether he is allowed to do so. Of course this may be done with regular if conditions, but probably something like CanCan or Pundit may be preferrable. By the way, I covered these solutions as well https://www.sitepoint.com/straightforward-rails-authorization-with-pundit/  https://www.sitepoint.com/cancancan-rails-authorization-dance/

**Comment by ghost** [comment]
I also use Cancancan :)
But except this specific permission, how can i do to implement your system only between to different devise users ?

**Comment by bodrovis** [comment]
Unfortunately, it seems things are a bit complex here so I can't just present a simple solution in two lines of code. You may read these discussions https://stackoverflow.com/questions/9472852/devise-and-multiple-user-models?rq=1https://stackoverflow.com/questions/19306731/multiple-models-in-devise about multiple models. Some people suggest using polymorhpic associations, some - different models and controllers and some prefer role-based system with Pundit. Just pick a solution you prefer and dig in that direction. I'd be happy to assist but that can't be done in 5 minutes - some researching should be done. Btw, you've suggested an interesting topic for my next article - Devise with multiple models. :)

**Comment by ghost** [comment]
@bodrovis ok i understand, that's really specific for my app. I need two devise users cause Proprietaire is like seller and Campeur is like customers. Proprietaire can only edit specific object to sell (Camping) and Campeur can only reserve a camping.

I m trying to implement a system to allow those 2 users to talk about reservation so I need discution between us. Maybe the solution can be a boolean column to specify this particular user is a Proprietaire and this user is Campeur. But I m not sure...

I  m exciting to read your futur topics :)

**Comment by bodrovis** [comment]
You know I believe the best course of actions is have ONE model with a property `role`: seller or customer. Or maybe just a boolean `seller` - if set to `false`, then it's a customer. Then just implement some conditions before starting a new conversation.

**Comment by ghost** [comment]
Ok thanks for your reply. I will implement this on a new branch.

**Comment by bodrovis** [comment]
You're welcome, good luck!
