### ISSUE TITLE
action cable messaging system tutorial not working

### ISSUE THREAD

**Issue by zzz6519003** [bodrovis/Sitepoint-source#11]
I followed your path, but it says
uninitialized constant PersonalMessage::NotificationBroadcastJob

Extracted source (around line #9):

```
  after_create_commit do
    conversation.touch
    NotificationBroadcastJob.perform_later(self)
  end
  
end
```

**Comment by bodrovis** [comment]
Check that you've named everything properly, that file with the job has the correct name as well. It is very important and your error suggests that some naming is done incorrectly.
