### ISSUE TITLE
Doesn't work locally...

### ISSUE THREAD

**Issue by biologistbrian** [bodrovis/Sitepoint-source#17]
Just did git clone, bundle, rake db:create, migrate, rails s.  It fires up nicely, but the automatic refresh between the two doesn't work.

**Comment by bodrovis** [comment]
Could you please check this guide and provide more info about your issue https://github.com/bodrovis/Sitepoint-source/blob/master/CONTRIBUTING.md ?

**Comment by bodrovis** [comment]
Closed as inactive. Feel free to re-open but do provide relevant info about the issue
