### ISSUE TITLE
Everything is working but when I try to send a message, after submitting the form it gives me this error message: No route matches [POST] "/chat_rooms/1"

### ISSUE THREAD

**Issue by samreenmalla** [bodrovis/Sitepoint-source#18]
The tutorial I followed is:
https://github.com/bodrovis/Sitepoint-source/tree/master/Chat_with_ActionCable_and_Devise
 
The full trace of the error is:

actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

Using Linux mint, rails version 5.2.0 and ruby version 2.4.1

**Comment by bodrovis** [comment]
Thanks for the detailed info! If this error message is being the displayed,  it means you are redirected to another page it seems. This, however, should not happen - the message should be sent asynchronously instead. Therefore, I suspect there is a problem with JS/Coffee somewhere. Specifically, this event here https://github.com/bodrovis/Sitepoint-source/blob/master/Chat_with_ActionCable_and_Devise/app/assets/javascripts/channels/rooms.coffee#L26 should be processed properly. Do you observe any errors in the browser's console perhaps?

Also, I'd suggest making sure that you are subscribed to ActionCable. To check that, https://github.com/bodrovis/Sitepoint-source/blob/master/Chat_with_ActionCable_and_Devise/app/assets/javascripts/channels/rooms.coffee#L13 you may tweak this line like that:

```coffee
connected: ->console.log('connected')
```

This message should be displayed in the browser's console.

**Comment by samreenmalla** [comment]
Actually, I converted the room.coffee file to room.js since the coffee file was giving a lot of error. Here is my room.js file:
```js
jQuery(document).on('turbolinks:load', function() {
  var messages, messages_to_bottom;
  messages = $('#messages');
  if ($('#messages').length > 0) {
    messages_to_bottom = function() {
      return messages.scrollTop(messages.prop("scrollHeight"));
    };
    messages_to_bottom();
    App.global_chat = App.cable.subscriptions.create({
      channel: "ChatRoomsChannel",
      chat_room_id: messages.data('chat-room-id')
    }, {
      connected: function() {},
      // Called when the subscription is ready for use on the server
      disconnected: function() {},
      // Called when the subscription has been terminated by the server
      received: function(data) {
        messages.append(data['message']);
        return messages_to_bottom();
      },
      send_message: function(message, chat_room_id) {
        return this.perform('send_message', {
          message: message,
          chat_room_id: chat_room_id
        });
      }
    });
    return $('#new_message').submit(function(e) {
      var $this, textarea;
      $this = $(this);
      textarea = $this.find('#message_body');
      if ($.trim(textarea.val()).length > 1) {
        App.global_chat.send_message(textarea.val(), messages.data('chat-room-id'));
        textarea.val('');
      }
      return e.preventDefault();
    });
  }
});

return false;
```

**Comment by bodrovis** [comment]
Okay then, try to tweak `connected: function() {},` with the `console.log`. Also I'd suggest adding `return  false` to the `$('#new_message').submit`, so it becomes:

```js
$('#new_message').submit(function(e) {
      e.preventDefault(); // this one is here

      var $this, textarea;
      $this = $(this);
      textarea = $this.find('#message_body');
      if ($.trim(textarea.val()).length > 1) {
        App.global_chat.send_message(textarea.val(), messages.data('chat-room-id'));
        textarea.val('');
      }
     return false;
    });
```

**Comment by samreenmalla** [comment]
Not working. Gives the same error. The server log is as follows:
ActionController::RoutingError (No route matches [POST] "/chat_rooms/1"):
  
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by bodrovis** [comment]
So, have you checked the browser's console? Did you make sure that ActionCable is really working  and the subscription exists as I explained below (with the `console.log` statement)? Maybe, you can simply share your full app and I'll fix it?...

**Comment by samreenmalla** [comment]
Here is a link to my repo: https://github.com/samreenmalla/Chatapp

**Comment by bodrovis** [comment]
Well, that's why I asked about errors in the browser's console. It says that jQuery is not defined because the order of the lines is incorrect here: https://github.com/samreenmalla/Chatapp/blob/master/app/assets/javascripts/application.js#L13 It should be 

```
//= require jquery
//= require cable
```

because otherwise inside your cable-related code you are relying on jQuery that is yet not loaded.

And, thing number two: https://github.com/samreenmalla/Chatapp/blob/master/app/channels/application_cable/connection.rb#L7 this should be

```ruby
logger.add_tags 'ActionCable', current_user.email
```

**Comment by samreenmalla** [comment]
Did this and the error is gone. But it doesn't show the messages in the chat room and also gives an exception. The server logs are:
 ↳ app/channels/application_cable/connection.rb:14
There was an exception - NoMethodError(undefined method `email' for nil:NilClass)
/home/samreen/ruby/Chatex/app/channels/application_cable/connection.rb:7:in `connect'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/connection/base.rb:169:in `handle_open'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:60:in `block in invoke'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:41:in `block in work'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `block in with_database_connections'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `block in tag'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `tag'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `with_database_connections'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/engine.rb:62:in `block (4 levels) in <class:Engine>'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/engine.rb:57:in `block (3 levels) in <class:Engine>'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:40:in `work'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:58:in `invoke'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:53:in `block in async_invoke'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
Finished "/cable/" [WebSocket] for 127.0.0.1 at 2018-07-06 17:14:12 +0545
Started GET "/cable" for 127.0.0.1 at 2018-07-06 17:14:13 +0545
Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2018-07-06 17:14:13 +0545
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 4], ["LIMIT", 1]]
  ↳ app/channels/application_cable/connection.rb:14
There was an exception - NoMethodError(undefined method `email' for nil:NilClass)
/home/samreen/ruby/Chatex/app/channels/application_cable/connection.rb:7:in `connect'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/connection/base.rb:169:in `handle_open'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:60:in `block in invoke'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:41:in `block in work'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `block in with_database_connections'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `block in tag'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `tag'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `with_database_connections'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/engine.rb:62:in `block (4 levels) in <class:Engine>'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/engine.rb:57:in `block (3 levels) in <class:Engine>'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:40:in `work'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:58:in `invoke'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/actioncable-5.2.0/lib/action_cable/server/worker.rb:53:in `block in async_invoke'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/samreen/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

**Comment by bodrovis** [comment]
I'll try to debug this further when I have time

**Comment by samreenmalla** [comment]
Okay. And thank you so much for helping me with this. Really grateful.

**Comment by bodrovis** [comment]
It does not work because of typos in some places. I can't guarantee I found all, but at least the messages now appear for me:

- https://github.com/samreenmalla/Chatapp/blob/master/app/channels/chat_rooms_channel.rb#L3 - should be `subscribed`
- https://github.com/samreenmalla/Chatapp/blob/master/app/channels/application_cable/connection.rb#L6 - `self.current_user`. `self` points to the current scope of execution
- https://github.com/samreenmalla/Chatapp/blob/master/app/jobs/message_broadcast_job.rb#L5 - `broadcast`

**Comment by samreenmalla** [comment]
Corrected the typos but the error is persistent. It shows an exception in connection.rb in line with `env[warden].user`

**Comment by samreenmalla** [comment]
Thank you so much for helping. The app finally works. I am going to close this issue. Thanks :smile:

**Comment by samreenmalla** [comment]
``
