### ISSUE TITLE
ActiveRecord:UnknownAttributeError Public_Activity Gem

### ISSUE THREAD

**Issue by RailsCod3rFuture** [bodrovis/Sitepoint-source#5]
When I try to create a new post, Public Activity intervenes and I'm unable to complete the request. I will post the controller_contents and stacktrace below.

``` ruby
class Post < ActiveRecord::Base
  include PublicActivity::Model

  tracked owner: Proc.new {|controller, model| controller.current_user ? controller.current_user : nil },
          photo: proc {|controller, model| model.photo },
          body: proc {|controller, model| model.body }

  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
  acts_as_commentable
  acts_as_votable
  default_scope -> { order(created_at: :desc) }
  validates :body, presence: true, length: {maximum: 150}
  validates :photo, presence: true #CarrierWave
  mount_uploader :photo, PhotoUploader
end
```

_activities.html.erb

```
<div class="col-md-4">
  <ul class="list-group">
    <% @activities.each do |activity| %>
        <li class="list-group-item">
          <span class="glyphicon glyphicon-<%= activity.key.match(/\.(.*)/)[1] %>"></span>
          <small class="text-muted"><%= activity.created_at.strftime('%H:%M:%S %-d %B %Y') %></small><br/>
          <strong><%= activity.owner ? activity.owner.username : 'Guest' %></strong>
          <%= render_activity(activity, display: :i18n) %>
          <% if activity.trackable %>
              "<%= link_to activity.trackable.body, post_path(activity.trackable) %>"
              "<%= link_to activity.trackable.photo, post_path(activity.trackable) %>"
          <% elsif activity.photo %>
              <span class="text-muted">"<%= activity.photo %>"</span>
          <% else %>
              with unknown post
          <% end %>
        </li>
    <% end %>
  </ul>
</div>
```

Posts_Controller.rb

``` ruby
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_filter :find_post, only: [:show, :like, :destroy]
  before_action :correct_user, only: [:destroy]
  respond_to :json, :html


  def index
    @user = User.find(params[:id])
    @post_items = Post.all.paginate(page: params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @new_comment = Comment.build_from(@post, current_user.id, "")
  end

  def new
    @post = Post.new
    @maximum_length = Post.validators_on(:body).first.options[:maximum]
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_params)

    if @post.save
      flash[:success] = "New Moment Posted"
      redirect_to @post
    else
      flash[:danger] = @post.errors.full_messages.to_sentence
      redirect_to root_url
    end
  end

  def destroy
    if @post.user == current_user
    @post.destroy
    redirect_to users_index_path
    flash[:success] = "Moment Deleted!"
    else
      redirect_to :back
      flash[:danger] = "Unable to delete Moment"
    end
  end

  def like
    @post = Post.find(params[:id])
    without_tracking do
      @post.liked_by current_user
    end
    @post.create_activity :like
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render layout: false }
    end
  end

  def unlike
    @post = Post.find(params[:id])
    @post.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render layout: false }
    end
  end

  private
  def post_params
    params.require(:post).permit(:body, :photo)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end

  def without_tracking
    Post.public_activity_off
    yield if block_given?
    Post.public_activity_on
  end
end
```

Stacktrace/Development log
ActiveRecord::UnknownAttributeError (unknown attribute 'photo' for PublicActivity::Activity.):
  app/controllers/posts_controller.rb:27:in `create'

Cannot render console with content type multipart/form-dataAllowed content types: [#<Mime::Type:0x38b9878 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html">, #<Mime::Type:0x38b8d68 @synonyms=[], @symbol=:text, @string="text/plain">, #<Mime::Type:0x38a1ff8 @synonyms=[], @symbol=:url_encoded_form, @string="application/x-www-form-urlencoded">]

**Comment by bodrovis** [comment]
This line causes your problems:

``` ruby
body: proc {|controller, model| model.photo }
```

You have a `photo` method, but there is no such column, therefore the gem does not know what to track. http://www.sitepoint.com/uploading-files-with-paperclip/ here is my article on paperclip, refer to the Integrating section to learn which attributes are actually present so that you can track them.

**Comment by RailsCod3rFuture** [comment]
I was trying to access the body and photo attributes for the Post model.

  create_table "posts", force: :cascade do |t|
    t.string   "body"
    t.integer  "user_id"
    t.datetime "created_at",         null: false
    t.datetime "updated_at",         null: false
    t.string   "photo"
    t.string   "video"
    t.string   "video_file_name"
    t.string   "video_content_type"
    t.integer  "video_file_size"
    t.datetime "video_updated_at"
  end

Also, I'm using CarrierWave for uploading photos since paperclip is not working correctly with my build.

**Comment by RailsCod3rFuture** [comment]
I added the link_to and to image_tag. "<%= link_to(image_tag(activity.trackable.photo.url(:medium)), post_path(activity.trackable)) %>"

**Comment by bodrovis** [comment]
Ah, that's carrierwave.... Well, I don't have many guesses here. Is your upload is working as expected? If yes, you might try disabling carrierwave completely and see whether public_activity works. If yes, then the carrierwave is messing everytinh up.

**Comment by RailsCod3rFuture** [comment]
There must be a bug in either carrierwave or public_activity causing this issue. Do you know of any other ways that I can approach tracking the post model?

**Comment by RailsCod3rFuture** [comment]
I followed your advice and added a photo column to the activities table. Now, I'm receiving this error when I render the _activities.html.erb view that you provided.

ActionView::Template::Error (Missing partial public_activity/post/_create with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder, :haml]}. Searched in:

**Comment by bodrovis** [comment]
I didn't advice to do that as this makes little sense :) I just thought that you are using paper_clip and this way should use not `photo`, but some other solumn for tracking. You should access photo and body via `trackable` which is a polymorphic association. I am pretty sure that something is not working inside your Post model, not within the public_activity itself. Once again what I'm suggesting is disabling carrierwave for now and see if the error persists. You know, just comment out all the lines related to carrierwave in your model.

**Comment by RailsCod3rFuture** [comment]
Public_Activity was searching for the CarrierWave photo column, but the method didn't exist within the scope of Public_Activity. I added photo as a custom field instead. https://github.com/chaps-io/public_activity/wiki/%5BHow-to%5D-Use-custom-fields-on-Activity

**Comment by bodrovis** [comment]
Well, yes, seems like my guess was pretty much correct. Glad you've solved it!

**Comment by RailsCod3rFuture** [comment]
Before we conclude, why is Public_Activity searching for a Public_Activity Folder and view? I don't see this folder in the app you've uploaded.

ActionView::MissingTemplate in Users#notifications
Missing partial public_activity/post/_create with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder, :haml]}. Searched in:

**Comment by bodrovis** [comment]
It's the default behavior https://github.com/chaps-io/public_activity#activity-views Follow the steps http://www.sitepoint.com/activity-feeds-rails/ in the Displaying the Activity Feed section and you'll notice it:

**public_activity expects that there is a public_activity folder inside the views that, in turn, has a story folder (or any other folder with a singular name of the model that is related to the specific activity). Inside the story directory, there should be the following partials: _create.html.erb, _update.html.erb, _destroy.html.erb. Each partial, as you’ve probably guessed, is rendered for the corresponding action. Inside those partials there is a local variable activity (aliased as a) available.**

**Comment by RailsCod3rFuture** [comment]
It's rendering the notifications view now. Thank you.

**Comment by bodrovis** [comment]
No problems!
