### ISSUE TITLE
Strong Params Changed

### ISSUE THREAD

**Issue by Ruffeng** [bodrovis/Sitepoint-source#8]
Hi @bodrovis .

I've found that rails has changed its way to permit a a field be on the whitelist.
Until now was:

`application_controller.rb`

```
def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :name
  devise_parameter_sanitizer.for(:account_update) << :name
end

```

The new way that Devise has changed is:

```
def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
```

I hope that this will help to get updated the tutorial.

Best!

Ruffeng

**Comment by bodrovis** [comment]
Thank you! This tut was written some time ago for a specific Devise version... Not sure it has to be modified but I'll add this as a comment.
